### ISSUE TITLE
Fix XML generation for FTL

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#2135]
**Describe the bug**

- [x] Update parsing for new Android XML changes
- [x] Update parsing for new iOS XML Changes
- [x] Verify `flaky="true"` is correctly persisted in the Flank XML [context](https://firebase-community.slack.com/archives/C72V6UW8M/p1629227697041400)
- [ ] Verify HTML report is correctly generated [context](https://firebase-community.slack.com/archives/C1MTSQ5QT/p1629226795170600?thread_ts=1628869085.134500&cid=C1MTSQ5QT)
- [x] Verify results are merged properly [context](https://firebase-community.slack.com/archives/C1MTSQ5QT/p1628869085134500)

---

iOS XML change

Current XML
```xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='PassingUITests' hostname='localhost' tests='1' failures='0' skipped='0' errors='0' time='19.216'>
    <properties />
    <testcase name='testPasses()' classname='PassingUITests' time='19.215' />
    <system-out />
    <system-err />
  </testsuite>
  <testsuite name='PassingUnitTests' hostname='localhost' tests='1' failures='0' skipped='0' errors='0' time='5.004'>
    <properties />
    <testcase name='testPasses()' classname='PassingUnitTests' time='5.003' />
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
```

New XML

```xml
<testsuites>
<testsuite name="" hostname="localhost" tests="2" failures="0" skipped="0" errors="0" time="24.562">
<properties/>
<testcase name="testPasses" classname="PassingUnitTests.PassingUnitTests" time="5.015"/>
<testcase name="testPasses" classname="PassingUITests.PassingUITests" time="19.547"/>
<system-out/>
<system-err/>
</testsuite>
</testsuites>
```

- Test suite is now empty
- Previous testsuite name is added as prefix to the classname

---

Firebase Test Lab has changed the XML format for all test results. The new format for both Android and iOS looks like this:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='' hostname='localhost' tests='4' failures='0' skipped='0' errors='0' time='12.671'>
    <properties />
      <!-- testcase here -->
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
```

Previously Android did not have a `testsuites` node. Now both Android and iOS have a `testsuites` node.

The latest Flank release is incorrectly merging the XML files. Example of the old xml
```
<testsuites>
<testsuite name="blueline-28-en-portrait#" tests="45" failures="6" errors="0" skipped="0" time="2475.330" timestamp="2021-08-11T00:05:40" hostname="localhost">
...
</testsuite>
</testsuites>
```

Example of `flank v21.08.0` incorrectly merging the new XML format:

```
<testsuites>
<testsuite name="blueline-28-en-portrait" tests="4" failures="3" flakes="0" errors="0" skipped="0" time="532.033" timestamp="2021-08-13T04:40:01" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="4" failures="3" flakes="0" errors="0" skipped="0" time="520.851" timestamp="2021-08-13T04:40:00" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="5" failures="4" flakes="0" errors="0" skipped="0" time="658.609" timestamp="2021-08-13T04:40:00" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="5" failures="4" flakes="0" errors="0" skipped="0" time="698.251" timestamp="2021-08-13T04:40:00" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="10" failures="4" flakes="0" errors="0" skipped="3" time="355.588" timestamp="2021-08-13T04:39:59" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="4" failures="2" flakes="0" errors="0" skipped="0" time="612.359" timestamp="2021-08-13T04:40:01" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="5" failures="5" flakes="0" errors="0" skipped="0" time="858.132" timestamp="2021-08-13T04:40:02" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="5" failures="5" flakes="0" errors="0" skipped="0" time="861.819" timestamp="2021-08-13T04:40:01" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="4" failures="2" flakes="0" errors="0" skipped="0" time="633.812" timestamp="2021-08-13T04:40:00" hostname="localhost">
...
</testsuite>
<testsuite name="blueline-28-en-portrait" tests="5" failures="3" flakes="0" errors="0" skipped="0" time="674.248" timestamp="2021-08-13T04:40:00" hostname="localhost">
...
</testsuite>
</testsuites>
```

**To Reproduce**
> Steps to reproduce the behavior:

1. Run test Android on test lab
2. See generated XML

**Expected behavior**
> A clear and concise description of what you expected to happen.

XML is merged properly.

**Additional context**
> Add any other context about the problem here.

See more details here:
https://firebase-community.slack.com/archives/C1MTSQ5QT/p1628869085134500

**Comment by bootstraponline** [comment]
FTL has rolled back the change that broke flank users.

https://firebase-community.slack.com/archives/C1MTSQ5QT/p1628879334143200?thread_ts=1628869085.134500&cid=C1MTSQ5QT

**Comment by piotradamczyk5** [comment]
hey @bootstraponline 
 should we fix this or not?

**Comment by michaelzoech** [comment]
Talked about this with @bootstraponline yesterday. I think these are now 2 issues:

1. FTL making a change in the produced JUnit XML
2. Flank not aggregating shards in the merged XML? Should it?

For 1. this change will be coming in FTL. Flank should adjust to parse JUnit XML files that have or have not a `<testsuites>` root node. On iOS this has been the case like since the beginning. On Android this change will be coming once this accepted by Flank. This will unify the XML format produced by FTL.

**Comment by bootstraponline** [comment]
Another issue was reported today, users are no longer seeing `flaky="true"` in the JUnit xml 

https://firebase-community.slack.com/archives/C72V6UW8M/p1629227697041400

**Comment by bootstraponline** [comment]
@piotradamczyk5 yeah I think we should fix this. The merging behavior has a regression. I updated the main issue with some more details.

**Comment by piotradamczyk5** [comment]
I will create proper tasks today based on all information which we currently have
